config/routes.rb
Rails.application.routes.draw do
  resources :aisles
  resources :products
  resources :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  Rails.application.routes.draw do
    resources :products, :users, :aisles
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/aisle.rb
class Aisle < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/aisles_controller.rb
class AislesController < ApplicationController
  before_action :set_headers, :set_aisle, only: [:show, :update, :destroy]

  # GET /aisles
  def index
    @aisles = Aisle.all
    json_response(@aisles)
  end

  # POST /todos
  def create
    @aisles = Aisle.create!(user_params)
    json_response(@aisles, :created)
  end

  # GET /todos/:id
  def show
    json_response(@aisles)
  end

  # PUT /todos/:id
  def update
    @aisles.update(user_params)
    head :no_content
  end

  # DELETE /todos/:id
  def destroy
    @aisles.destroy
    head :no_content
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def aisle_params
    params.require(:aisle).permit(:name)
  end

  def aisle_params
    params.require(:aisle).permit(:name)
    params.permit(:name)
  end

  def set_aisle
    @aisle = Aisle.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Response
  include ExceptionHandler
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok, headers = 'Access-Control-Allow-Origin: *')
    render json: object, status: status
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
before_action :set_headers, :set_product, only: [:show, :update, :destroy]
before_action


  # GET /users
  def index
    @products = Product.all
    json_response(@products)
  end

  # POST /todos
  def create
    @products = Product.create!(user_params)
    json_response(@products, :created)
  end

  # GET /todos/:id
  def show
    json_response(@products)
  end

  # PUT /todos/:id
  def update
    @products.update(user_params)
    head :no_content
  end

  # DELETE /todos/:id
  def destroy
    @products.destroy
    head :no_content
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :image, :price)
    params.permit(:name, :description, :image, :price)
  end

  def set_headers
    response.headers['Content-Type'] = 'application/vnd.api+json'
  end

  def set_product
    @products = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_headers, :set_user, only: [:show, :update, :destroy]

  # GET /users
  def index
    @users = User.all
    json_response(@users)
  end

  # POST /todos
  def create
    @users = User.create!(user_params)
    json_response(@users, :created)
  end

  # GET /todos/:id
  def show
    json_response(@users)
  end

  # PUT /todos/:id
  def update
    @users.update(user_params)
    head :no_content
  end

  # DELETE /todos/:id
  def destroy
    @users.destroy
    head :no_content
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_id)
    params.permit(:first_name, :last_name, :user_id)
  end

  def set_headers
    response.headers['Content-Type'] = 'application/vnd.api+json'
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/aisles_helper.rb
module AislesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/aisles/_form.html.erb
<%= form_with(model: aisle, local: true) do |form| %>
  <% if aisle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aisle.errors.count, "error") %> prohibited this aisle from being saved:</h2>

      <ul>
      <% aisle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :aisle_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aisles/edit.html.erb
<h1>Editing Aisle</h1>

<%= render 'form', aisle: @aisle %>

<%= link_to 'Show', @aisle %> |
<%= link_to 'Back', aisles_path %>

app/views/aisles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aisles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aisles.each do |aisle| %>
      <tr>
        <td><%= aisle.name %></td>
        <td><%= link_to 'Show', aisle %></td>
        <td><%= link_to 'Edit', edit_aisle_path(aisle) %></td>
        <td><%= link_to 'Destroy', aisle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aisle', new_aisle_path %>

app/views/aisles/new.html.erb
<h1>New Aisle</h1>

<%= render 'form', aisle: @aisle %>

<%= link_to 'Back', aisles_path %>

app/views/aisles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @aisle.name %>
</p>

<%= link_to 'Edit', edit_aisle_path(@aisle) %> |
<%= link_to 'Back', aisles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Market</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :product_image %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :user_last_name %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.user_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.user_id %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>